const
    USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS",
    USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
    USER_REGISTER_ERROR = "USER_REGISTER_ERROR",
    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
    USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS",
    USER_LOGIN_ERROR = "USER_LOGIN_ERROR",
    USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",
    USER_DELETE_SUCCESS = "USER_UPDATE_SUCCESS",
    USER_SET_TOKEN_SUCCESS = "USER_SET_TOKEN_SUCCESS";

export {
    USER_LOAD_SUCCESS,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_ERROR,
    USER_LOGIN_SUCCESS,
    USER_LOGOUT_SUCCESS,
    USER_LOGIN_ERROR,
    USER_UPDATE_SUCCESS,
    USER_DELETE_SUCCESS,
    USER_SET_TOKEN_SUCCESS
}
